import type { L } from './types'

export interface Card {
  t: L // Titel
  b: L // Erklärung
}

// Lernkarten pro Lektion — die „Kapitel" vor dem Quiz (Duolingo-Style: erst lernen, dann üben)
export const learnCards: Record<string, Card[]> = {
  /* ================= 48 LAWS OF POWER ================= */
  'p48-1': [
    { t: { de: 'Gesetz 1 · Überstrahle niemals den Meister', en: 'Law 1 · Never outshine the master' },
      b: { de: 'Vorgesetzte müssen sich stets als die Hellsten fühlen. Wer sein Talent zu offen zeigt, erntet statt Belohnung Neid und Groll von oben.', en: 'Superiors must always feel like the brightest. Showing off your talent earns you envy and resentment from above instead of reward.' } },
    { t: { de: 'Gesetz 2 · Misstraue Freunden, nutze Feinde', en: 'Law 2 · Distrust friends, use enemies' },
      b: { de: 'Freunde nehmen dich als selbstverständlich und werden schnell neidisch. Ein ehemaliger Feind dient ergebener — er muss sich beweisen.', en: 'Friends take you for granted and turn envious. A former enemy serves more devotedly — he has to prove himself.' } },
    { t: { de: 'Gesetz 3 · Verberge deine Absichten', en: 'Law 3 · Conceal your intentions' },
      b: { de: 'Wer nicht weiß, was du willst, kann sich nicht wehren. Bismarck hielt eine Friedensrede, während er längst den Krieg plante.', en: 'If nobody knows what you want, nobody can defend against it. Bismarck gave a peace speech while already planning war.' } },
    { t: { de: 'Gesetz 4 · Sage stets weniger als nötig', en: 'Law 4 · Always say less than necessary' },
      b: { de: 'Je mehr du redest, desto gewöhnlicher wirkst du. Ludwig XIV. antwortete oft nur: „Ich werde sehen" — Schweigen vergrößert deine Aura.', en: 'The more you talk, the more ordinary you seem. Louis XIV often replied only "I shall see" — silence grows your aura.' } },
    { t: { de: 'Gesetz 5 · Schütze deinen Ruf mit dem Leben', en: 'Law 5 · Guard your reputation with your life' },
      b: { de: 'Der Ruf entscheidet, wie die Welt dich behandelt — er geht dir voraus. Schütze deinen eigenen, und greife den deiner Gegner an.', en: 'Reputation decides how the world treats you — it precedes you. Guard your own, and attack your enemies\'.' } },
  ],
  'p48-2': [
    { t: { de: 'Gesetz 6 · Erregte um jeden Preis Aufmerksamkeit', en: 'Law 6 · Court attention at all costs' },
      b: { de: 'Aufmerksamkeit ist eine Währung: Sichtbarkeit erzeugt Wert. Schlecht aufzufallen ist besser als gar nicht aufzufallen.', en: 'Attention is currency: visibility creates value. Being noticed for bad reasons beats not being noticed at all.' } },
    { t: { de: 'Gesetz 7 · Lass andere arbeiten — nimm die Ehre', en: 'Law 7 · Let others work — take the credit' },
      b: { de: 'Nutze die Arbeit anderer für deine Zwecke, aber behalte die Anerkennung. Deine Zeit ist kostbarer als ihre.', en: 'Use others\' work for your goals, but keep the credit. Your time is more precious than theirs.' } },
    { t: { de: 'Gesetz 8 · Zwinge andere, zu dir zu kommen', en: 'Law 8 · Make others come to you' },
      b: { de: 'Wer kommen muss, agiert auf deinem Terrain — und in deiner Falle. Lege Köder aus, statt zu verfolgen.', en: 'Whoever must come to you acts on your terrain — and in your trap. Lay bait instead of chasing.' } },
    { t: { de: 'Gesetz 9 · Gewinne durch Taten, nie durch Argumente', en: 'Law 9 · Win through actions, never arguments' },
      b: { de: 'Argumente erzeugen Groll und ändern keine Meinung. Zeige es stattdessen — Demonstration schlägt Erklärung.', en: 'Arguments breed resentment and change no minds. Demonstrate instead — showing beats explaining.' } },
    { t: { de: 'Gesetz 10 · Meide die Unglücklichen', en: 'Law 10 · Avoid the unhappy' },
      b: { de: 'Unglück und Elend sind ansteckend wie Krankheiten. Umgebe dich mit Glücklichen und Effizienten — Emotionen übertragen sich.', en: 'Misery is contagious like a disease. Surround yourself with the happy and efficient — emotions transfer.' } },
  ],
  'p48-3': [
    { t: { de: 'Gesetz 11 · Mach dich unverzichtbar', en: 'Law 11 · Become indispensable' },
      b: { de: 'Mache andere von dir abhängig: Wer gebraucht wird, kann nicht ersetzt werden. Abhängigkeit ist eine Form von Macht.', en: 'Make others depend on you: those who are needed cannot be replaced. Dependence is a form of power.' } },
    { t: { de: 'Gesetz 12 · Selektive Ehrlichkeit entwaffnet', en: 'Law 12 · Selective honesty disarms' },
      b: { de: 'Eine gezielte ehrliche, großzügige Geste baut Vertrauen auf — ein Mantel für größere Manöver.', en: 'One targeted honest, generous gesture builds trust — a cloak for larger maneuvers.' } },
    { t: { de: 'Gesetz 13 · Appelliere ans Eigeninteresse', en: 'Law 13 · Appeal to self-interest' },
      b: { de: 'Wenn du um Hilfe bittest: Zeige, was DER ANDERE gewinnt — nicht was du brauchst. Mitleid zu erbitten macht dich schwach.', en: 'When asking for help: show what THE OTHER gains — not what you need. Begging for pity makes you weak.' } },
    { t: { de: 'Gesetz 14 · Gib dich als Freund, arbeite als Spion', en: 'Law 14 · Pose as a friend, work as a spy' },
      b: { de: 'Freundliche Offenheit lockert Zungen. Sammle Informationen, ohne Verdacht zu erregen — Wissen über andere ist Macht.', en: 'Friendly openness loosens tongues. Gather information without raising suspicion — knowledge about others is power.' } },
    { t: { de: 'Gesetz 15 · Zerschmettere deinen Feind vollständig', en: 'Law 15 · Crush your enemy totally' },
      b: { de: 'Ein halb besiegter Feind erholt sich und rächt sich später. Was du begonnen hast, beende vollständig.', en: 'A half-defeated enemy recovers and takes revenge later. What you started, finish completely.' } },
  ],
  'p48-4': [
    { t: { de: 'Gesetz 16 · Abwesenheit erzeugt Respekt', en: 'Law 16 · Absence creates respect' },
      b: { de: 'Knappheit steigert den Wert: Wer ständig sichtbar ist, wird gewöhnlich. Ziehe dich zeitweise zurück — und man redet über dich.', en: 'Scarcity raises value: constant visibility makes you ordinary. Withdraw at times — and people will talk about you.' } },
    { t: { de: 'Gesetz 17 · Bleib unberechenbar', en: 'Law 17 · Stay unpredictable' },
      b: { de: 'Halte andere in schwebender Unruhe. Berechenbarkeit macht dich kontrollierbar — Unberechenbarkeit erschöpft deine Gegner.', en: 'Keep others in suspense. Predictability makes you controllable — unpredictability exhausts your opponents.' } },
    { t: { de: 'Gesetz 18 · Baue keine Festungen', en: 'Law 18 · Build no fortresses' },
      b: { de: 'Isolation schneidet dich von Information und Einfluss ab. Die Welt bewegt sich in der Menge — bleib in Kontakt.', en: 'Isolation cuts you off from information and influence. The world moves in the crowd — stay in contact.' } },
    { t: { de: 'Gesetz 19 · Wisse, mit wem du es zu tun hast', en: 'Law 19 · Know who you\'re dealing with' },
      b: { de: 'Manche Menschen rächen sich maßlos, andere lassen sich täuschen. Wähle Opfer und Gegner mit Bedacht — provoziere nie den Falschen.', en: 'Some people take boundless revenge, others are easily fooled. Choose victims and opponents carefully — never provoke the wrong one.' } },
    { t: { de: 'Gesetz 20 · Committe dich zu niemandem', en: 'Law 20 · Commit to no one' },
      b: { de: 'Wer unabhängig bleibt, wird von beiden Seiten umworben. Commitment macht berechenbar — Distanz erzeugt Wettbewerb um deine Gunst.', en: 'Stay independent and both sides will court you. Commitment makes you predictable — distance creates competition for your favor.' } },
  ],
  'p48-5': [
    { t: { de: 'Gesetz 21 · Spiele den Narren, um einen Narren zu fangen', en: 'Law 21 · Play a sucker to catch a sucker' },
      b: { de: 'Wirke harmloser, als du bist. Wer sich klug fühlen darf, senkt seine Wachsamkeit — und wird angreifbar.', en: 'Seem more harmless than you are. Those who feel smart lower their guard — and become vulnerable.' } },
    { t: { de: 'Gesetz 22 · Die Kapitulationstaktik', en: 'Law 22 · The surrender tactic' },
      b: { de: 'Verwandle Schwäche in Macht: Scheinbares Nachgeben entwaffnet den Sieger und kauft dir Zeit für den nächsten Zug.', en: 'Turn weakness into power: feigned surrender disarms the victor and buys you time for the next move.' } },
    { t: { de: 'Gesetz 23 · Konzentriere deine Kräfte', en: 'Law 23 · Concentrate your forces' },
      b: { de: 'Fokus an einem Punkt schlägt Zerstreuung. Verteile deine Energie nie gleichmäßig auf viele Ziele.', en: 'Focus at one point beats dispersion. Never spread your energy evenly across many goals.' } },
    { t: { de: 'Gesetz 24 · Der perfekte Höfling', en: 'Law 24 · The perfect courtier' },
      b: { de: 'Beherrsche Indirektion, Schmeichelei und Anpassung. Macht liegt beim Souverän — der kluge Höfling navigiert die höfische Politik.', en: 'Master indirection, flattery, and adaptation. Power lies with the sovereign — the smart courtier navigates court politics.' } },
    { t: { de: 'Gesetz 25 · Erschaffe dich neu', en: 'Law 25 · Re-create yourself' },
      b: { de: 'Akzeptiere nicht die Rolle, die andere dir geben. Dein Bild ist deine Schöpfung — wähle selbst, wie die Welt dich sieht.', en: 'Don\'t accept the role others give you. Your image is your creation — choose yourself how the world sees you.' } },
  ],
  'p48-6': [
    { t: { de: 'Gesetz 26 · Halte deine Hände sauber', en: 'Law 26 · Keep your hands clean' },
      b: { de: 'Unangenehmes erledigen andere für dich: Nutze Sündenböcke und Stellvertreter. Dein Image bleibt makellos.', en: 'Let others do the dirty work: use scapegoats and proxies. Your image stays spotless.' } },
    { t: { de: 'Gesetz 27 · Nutze das Glaubensbedürfnis', en: 'Law 27 · Exploit the need to believe' },
      b: { de: 'Menschen wollen verzweifelt an etwas glauben. Biete ihnen eine Sache, eine Verheißung — und sie folgen dir.', en: 'People desperately want to believe in something. Offer them a cause, a promise — and they will follow you.' } },
    { t: { de: 'Gesetz 28 · Tritt mit Kühnheit ins Handeln', en: 'Law 28 · Enter action with boldness' },
      b: { de: 'Halbherzigkeit erzeugt Zweifel. Kühnheit verwirrt Zögern, reißt Menschen mit und lässt Fehler klein wirken.', en: 'Half-heartedness breeds doubt. Boldness confuses hesitation, sweeps people along, and makes errors look small.' } },
    { t: { de: 'Gesetz 29 · Plane bis zum Ende', en: 'Law 29 · Plan all the way to the end' },
      b: { de: 'Sieh Konsequenzen und Reaktionen voraus, bevor du handelst. Wer das Ende plant, wird von Überraschungen nicht aus der Bahn geworfen.', en: 'Foresee consequences and reactions before acting. Those who plan the ending are not derailed by surprises.' } },
    { t: { de: 'Gesetz 30 · Lass alles mühelos erscheinen', en: 'Law 30 · Make it all look effortless' },
      b: { de: 'Zeige nie, wie hart du gearbeitet hast. Sichtbare Anstrengung macht dich gewöhnlich — Mühelosigkeit erzeugt Bewunderung.', en: 'Never show how hard you worked. Visible effort makes you ordinary — effortlessness creates admiration.' } },
  ],
  'p48-7': [
    { t: { de: 'Gesetz 31 · Kontrolliere die Optionen', en: 'Law 31 · Control the options' },
      b: { de: 'Gib anderen nur Wahlen, die dir beide nützen. Das Gefühl freier Wahl täuscht — beide Wege führen in dein Konzept.', en: 'Give others only choices that both benefit you. The feeling of free choice deceives — both paths lead into your plan.' } },
    { t: { de: 'Gesetz 32 · Spiele mit den Fantasien der Menschen', en: 'Law 32 · Play on people\'s fantasies' },
      b: { de: 'Die Wahrheit ist oft unbequem — Menschen träumen lieber. Wer die schöne Verheißung liefert, gewinnt.', en: 'Truth is often uncomfortable — people prefer to dream. Whoever delivers the beautiful promise wins.' } },
    { t: { de: 'Gesetz 33 · Finde die Daumenschraube', en: 'Law 33 · Find the thumbscrew' },
      b: { de: 'Jeder hat eine Schwäche: eine Unsicherheit, ein unstillbares Bedürfnis, eine Angst. Finde sie — und du hast den Hebel.', en: 'Everyone has a weakness: an insecurity, an insatiable need, a fear. Find it — and you have the lever.' } },
    { t: { de: 'Gesetz 34 · Sei königlich auf deine eigene Art', en: 'Law 34 · Be royal in your own fashion' },
      b: { de: 'Behandle dich selbst als Souverän — dann tun es andere auch. Deine Selbstachtung strahlt aus und setzt den Preis fest.', en: 'Treat yourself as sovereign — then others will too. Your self-respect radiates and sets the price.' } },
    { t: { de: 'Gesetz 35 · Meistere das Timing', en: 'Law 35 · Master the timing' },
      b: { de: 'Zu früh ist so fatal wie zu spät. Wer die Zeichen der Zeit liest und warten kann, handelt im richtigen Moment.', en: 'Too early is as fatal as too late. Those who read the signs of the times and can wait act at the right moment.' } },
  ],
  'p48-8': [
    { t: { de: 'Gesetz 36 · Verachte, was du nicht haben kannst', en: 'Law 36 · Despise what you cannot have' },
      b: { de: 'Aufmerksamkeit gibt Problemen Macht. Was du ignorierst, kann dich nicht treffen — kleinliche Aufmerksamkeit vergrößert kleine Probleme.', en: 'Attention gives problems power. What you ignore cannot touch you — petty attention enlarges small problems.' } },
    { t: { de: 'Gesetz 37 · Erschaffe fesselnde Spektakel', en: 'Law 37 · Create compelling spectacles' },
      b: { de: 'Bilder, Symbole und Inszenierungen erreichen Menschen tiefer als jedes Argument. Inszeniere deine Macht sichtbar.', en: 'Images, symbols and staging reach people deeper than any argument. Stage your power visibly.' } },
    { t: { de: 'Gesetz 38 · Denke frei — verhalte dich angepasst', en: 'Law 38 · Think freely — behave conventionally' },
      b: { de: 'Offene Abweichung erzeugt Feinde. Bewahre deine Originalität für dich und passe dich äußerlich an.', en: 'Open deviation creates enemies. Keep your originality to yourself and blend in outwardly.' } },
    { t: { de: 'Gesetz 39 · Rühre das Wasser auf', en: 'Law 39 · Stir up the waters' },
      b: { de: 'Mache Gegner emotional, damit sie Fehler begehen. Wer die Ruhe verliert, verliert die Kontrolle — bleib du ruhig.', en: 'Make opponents emotional so they make mistakes. Whoever loses calm loses control — you stay calm.' } },
    { t: { de: 'Gesetz 40 · Nichts ist gratis', en: 'Law 40 · Nothing is free' },
      b: { de: 'Das Gratis-Mittagessen gibt es nicht: Geschenke erzeugen Verpflichtungen. Zahle deinen eigenen Preis — das ist Freiheit.', en: 'There is no free lunch: gifts create obligations. Pay your own price — that is freedom.' } },
  ],
  'p48-9': [
    { t: { de: 'Gesetz 41 · Meide die Fußstapfen eines Großen', en: 'Law 41 · Avoid a great one\'s footsteps' },
      b: { de: 'Der Nachfolger eines Giganten wird immer verglichen und verliert. Schaffe deinen eigenen Raum statt seinen zu füllen.', en: 'A giant\'s successor is always compared and loses. Create your own space instead of filling his.' } },
    { t: { de: 'Gesetz 42 · Schlage den Hirten', en: 'Law 42 · Strike the shepherd' },
      b: { de: 'Unruhestifter ziehen ihre Macht aus der Gruppe. Isoliere den Anführer — und die Schafe zerstreuen sich.', en: 'Troublemakers draw power from the group. Isolate the leader — and the sheep scatter.' } },
    { t: { de: 'Gesetz 43 · Gewinne Herzen und Köpfe', en: 'Law 43 · Win hearts and minds' },
      b: { de: 'Zwang erzeugt Widerstand, Verführung erzeugt Anhänger. Arbeite an Gefühl und Verstand der Menschen.', en: 'Coercion breeds resistance, seduction breeds followers. Work on people\'s feelings and minds.' } },
    { t: { de: 'Gesetz 44 · Der Spiegel-Effekt', en: 'Law 44 · The mirror effect' },
      b: { de: 'Spiegle anderen ihr eigenes Verhalten zurück: Wer sein eigenes Spiel erlebt, verliert die Kontrolle — entwaffnet oder erzürnt.', en: 'Mirror others\' behavior back at them: experiencing their own game makes people lose control — disarmed or enraged.' } },
    { t: { de: 'Gesetz 45 · Predige Wandel in kleinen Dosen', en: 'Law 45 · Preach change in small doses' },
      b: { de: 'Zu viel Neues auf einmal erzeugt Rebellion. Predige Wandel laut — aber führe ihn langsam ein.', en: 'Too much novelty at once breeds rebellion. Preach change loudly — but introduce it slowly.' } },
  ],
  'p48-10': [
    { t: { de: 'Gesetz 46 · Wirke nie zu perfekt', en: 'Law 46 · Never appear too perfect' },
      b: { de: 'Perfektion erzeugt Neid und Feinde. Zeige kleine Makel — sie wirken menschlich und entwaffnen Neider.', en: 'Perfection breeds envy and enemies. Show small flaws — they seem human and disarm the envious.' } },
    { t: { de: 'Gesetz 47 · Gehe nicht über das Ziel hinaus', en: 'Law 47 · Do not go past the goal' },
      b: { de: 'Im Sieg Halt zu machen ist schwerer als zu siegen. Arroganz und Überschwang ruinieren das Gewonnene.', en: 'Stopping in victory is harder than winning. Arrogance and overreach ruin what was gained.' } },
    { t: { de: 'Gesetz 48 · Nimm Formlosigkeit an', en: 'Law 48 · Assume formlessness' },
      b: { de: 'Alles Feste wird berechenbar und verwundbar. Bleibe flüssig wie Wasser — passe dich an, ohne dich festzulegen.', en: 'Anything fixed becomes predictable and vulnerable. Stay fluid like water — adapt without committing to a form.' } },
    { t: { de: 'Meta · Die Gesetze als Werkzeuge', en: 'Meta · The laws as tools' },
      b: { de: 'Du musst die Gesetze kennen, auch wenn du sie nicht anwendest: Wer das Spiel nicht kennt, wird zur Spielfigur anderer.', en: 'You must know the laws even if you don\'t apply them: those who don\'t know the game become other people\'s pawns.' } },
  ],

  /* ================= 33 STRATEGIES OF WAR ================= */
  'war-1': [
    { t: { de: 'Strategie 1 · Erkläre deinen Feinden den Krieg', en: 'Strategy 1 · Declare war on your enemies' },
      b: { de: 'Polarität schafft Fokus: Wer klar benennt, wer der Gegner ist, verschwendet keine Energie an falsche Freunde und Illusionen.', en: 'Polarity creates focus: clearly naming your opponent wastes no energy on false friends and illusions.' } },
    { t: { de: 'Strategie 2 · Kämpfe nicht den letzten Krieg', en: 'Strategy 2 · Do not fight the last war' },
      b: { de: 'Was gestern funktionierte, ist heute veraltet. Vergangene Erfolge werden zur Falle — Strategen kämpfen die Gegenwart.', en: 'What worked yesterday is outdated today. Past successes become traps — strategists fight the present.' } },
    { t: { de: 'Strategie 3 · Bewahre deine Geistesgegenwart', en: 'Strategy 3 · Keep your presence of mind' },
      b: { de: 'Wer dich emotional macht, führt dich. Im Tumult der Ereignisse ist Ruhe die letzte Verteidigung.', en: 'Whoever makes you emotional controls you. Amidst turmoil, calm is the last defense.' } },
    { t: { de: 'Strategie 4 · Die Sterblichkeitsstrategie', en: 'Strategy 4 · The death-ground strategy' },
      b: { de: 'Auf „totem Grund" ohne Rückzug kämpfen Menschen am härtesten. Kultiviere Dringlichkeit — Rücken an die Wand schafft Fokus.', en: 'On "death ground" with no retreat, people fight hardest. Cultivate urgency — back to the wall creates focus.' } },
  ],
  'war-2': [
    { t: { de: 'Strategie 5 · Vermeide Groupthink', en: 'Strategy 5 · Avoid groupthink' },
      b: { de: 'Gruppen neigen zu Konformität. Kluge Führer hören viele Stimmen — aber die Entscheidung trifft einer, mit klarer Verantwortung.', en: 'Groups drift toward conformity. Smart leaders hear many voices — but one person decides, with clear ownership.' } },
    { t: { de: 'Strategie 6 · Segmentiere deine Kräfte', en: 'Strategy 6 · Segment your forces' },
      b: { de: 'Kleine, autonome Einheiten sind flexibler als ein starres Großheer: Sie entscheiden schnell vor Ort, das Zentrum hält den Rahmen.', en: 'Small autonomous units beat one rigid mass army: they decide fast on the ground while the center holds the frame.' } },
    { t: { de: 'Strategie 7 · Verwandle deinen Krieg in einen Kreuzzug', en: 'Strategy 7 · Turn your war into a crusade' },
      b: { de: 'Menschen kämpfen härter für eine Idee als für einen Sold. Lade den Kampf moralisch auf — eine Sache schafft Fanatismus.', en: 'People fight harder for an idea than for a paycheck. Charge the fight morally — a cause creates fanaticism.' } },
    { t: { de: 'Führung · Entscheide klar', en: 'Leadership · Decide clearly' },
      b: { de: 'Ungewisse Führung lähmt die Truppe. Entscheide, kommuniziere unmissverständlich — und die Truppe folgt.', en: 'Uncertain leadership paralyzes the troops. Decide, communicate unambiguously — and the troops follow.' } },
  ],
  'war-3': [
    { t: { de: 'Strategie 8 · Wähle deine Schlachten sorgfältig', en: 'Strategy 8 · Pick your battles carefully' },
      b: { de: 'Die perfekte Ökonomie: Jeder Kampf kostet Kraft. Kämpfe nur, wenn der Nutzen die Kosten übersteigt — der Weise lässt Scharmützel aus.', en: 'Perfect economy: every fight costs strength. Fight only when benefit exceeds cost — the wise skip skirmishes.' } },
    { t: { de: 'Strategie 9 · Drehe den Spieß um', en: 'Strategy 9 · Turn the tables' },
      b: { de: 'Wer nur reagiert, verliert. Aus scheinbarer Schwäche zum Gegenangriff umschalten ergreift die Initiative.', en: 'Those who only react lose. Switching from apparent weakness to counterattack seizes the initiative.' } },
    { t: { de: 'Strategie 10 · Bedrohliche Präsenz', en: 'Strategy 10 · Threatening presence' },
      b: { de: 'Der beste Kampf ist der, der gar nicht stattfindet: Abschreckung erspart dir tatsächliche Kämpfe.', en: 'The best battle is the one that never happens: deterrence spares you actual fights.' } },
    { t: { de: 'Strategie 11 · Tausche Raum gegen Zeit', en: 'Strategy 11 · Trade space for time' },
      b: { de: 'Raum ist billiger als Niederlage: Wer Territorium opfert und weicht, lebt, um später zurückzuschlagen.', en: 'Space is cheaper than defeat: those who sacrifice territory and yield live to strike back later.' } },
  ],
  'war-4': [
    { t: { de: 'Strategie 12 · Verliere Schlachten, gewinne den Krieg', en: 'Strategy 12 · Lose battles, win the war' },
      b: { de: 'Kleine taktische Verluste können strategisch klug sein — sie ködern Übermut. Die Grand Strategy dient dem großen Bild, nicht dem Ego.', en: 'Small tactical losses can be strategically wise — they bait overconfidence. Grand strategy serves the big picture, not the ego.' } },
    { t: { de: 'Strategie 13 · Kenne deinen Feind', en: 'Strategy 13 · Know your enemy' },
      b: { de: 'Information ist die halbe Schlacht: Wer die Denkweise, Muster und Schwächen des Gegners versteht, sieht seine Züge voraus.', en: 'Intelligence is half the battle: understanding the opponent\'s mindset, patterns and weaknesses lets you foresee his moves.' } },
    { t: { de: 'Strategie 14 · Die Blitzkrieg-Strategie', en: 'Strategy 14 · The blitzkrieg strategy' },
      b: { de: 'Überwältige Widerstand mit Geschwindigkeit und Plötzlichkeit: Der Gegner kann nicht reagieren, bevor es vorbei ist.', en: 'Overwhelm resistance with speed and suddenness: the opponent cannot react before it\'s over.' } },
    { t: { de: 'Strategie 15 · Die Forcing-Strategie', en: 'Strategy 15 · The forcing strategy' },
      b: { de: 'Kontrolliere die Dynamik, indem du den Gegner zu Zügen zwingst. Wer handeln muss, macht Fehler.', en: 'Control the dynamic by forcing the opponent into moves. Those who must act make mistakes.' } },
  ],
  'war-5': [
    { t: { de: 'Strategie 17 · Teile und herrsche', en: 'Strategy 17 · Divide and rule' },
      b: { de: 'Ein geeinter Feind ist stark. Säge Misstrauen zwischen den Verbündeten — und das Bündnis zerfällt von selbst.', en: 'A united enemy is strong. Sow distrust among the allies — and the alliance dissolves by itself.' } },
    { t: { de: 'Strategie 18 · Attackiere die weiche Flanke', en: 'Strategy 18 · Attack the soft flank' },
      b: { de: 'Indirektion schlägt Konfrontation: Die Front ist befestigt, die Flanke nicht. Finde die Verwundbarkeit statt frontal anzugreifen.', en: 'Indirection beats confrontation: the front is fortified, the flank is not. Find the vulnerability instead of attacking head-on.' } },
    { t: { de: 'Strategie 20 · Manövriere sie in die Schwäche', en: 'Strategy 20 · Maneuver them into weakness' },
      b: { de: 'Manöver erschöpfen und verwirren: Treibe den Gegner in Positionen, in denen er schwach ist. Der Sieg folgt der Erschöpfung.', en: 'Maneuvers exhaust and confuse: drive the opponent into positions where he is weak. Victory follows exhaustion.' } },
    { t: { de: 'Strategie 21 · Verhandle, während du vorrückst', en: 'Strategy 21 · Negotiate while advancing' },
      b: { de: 'Verhandlung ohne Druck ist Bettelei; Druck mit Verhandlung ist Strategie. Diplomatie läuft parallel zum Vorrücken.', en: 'Negotiation without pressure is begging; pressure with negotiation is strategy. Diplomacy runs parallel to advancing.' } },
    { t: { de: 'Strategie 22 · Wisse, wie man Dinge beendet', en: 'Strategy 22 · Know how to end things' },
      b: { de: 'Die Kunst des guten Endes: Sieger, die zu weit gehen, zerstören ihren Sieg. Wer das Ende nicht plant, wird vom Erfolg überrollt.', en: 'The art of the good ending: victors who go too far destroy their victory. Those who don\'t plan the ending get run over by success.' } },
  ],
  'war-6': [
    { t: { de: 'Strategie 23 · Webe Fakt und Fiktion zusammen', en: 'Strategy 23 · Blend fact and fiction' },
      b: { de: 'Die glaubwürdigste Täuschung enthält viel Wahres. Wahrnehmung ist das Schlachtfeld — Desinformation sieht real aus.', en: 'The most believable deception contains much truth. Perception is the battlefield — disinformation looks real.' } },
    { t: { de: 'Strategie 24 · Die Linie der geringsten Erwartung', en: 'Strategy 24 · The line of least expectation' },
      b: { de: 'Tue das Unerwartete: Was niemand erwartet, kann niemand abwehren. Außergewöhnlichkeit ist Strategie.', en: 'Do the unexpected: what nobody expects, nobody can defend against. Unconventionality is strategy.' } },
    { t: { de: 'Strategie 26 · Verweigere ihnen Ziele', en: 'Strategy 26 · Deny them targets' },
      b: { de: 'Wer kein Ziel bietet, kann nicht getroffen werden. Der Gegner schlägt ins Leere, verliert die Fassung und erschöpft sich.', en: 'Offering no target means you cannot be hit. The opponent strikes at air, loses composure and exhausts himself.' } },
    { t: { de: 'Strategie 31 · Zerstöre von innen', en: 'Strategy 31 · Destroy from within' },
      b: { de: 'Festungen fallen leichter durch Tore, die von innen geöffnet werden. Unterwandern statt stürmen.', en: 'Fortresses fall more easily through gates opened from inside. Infiltrate instead of storming.' } },
    { t: { de: 'Strategie 32 · Dominiere im Gewand des Gehorsams', en: 'Strategy 32 · Dominate in the cloak of obedience' },
      b: { de: 'Passive Aggression: Ungehorsam im Gewand des Gehorsams ist schwer angreifbar. Scheine zu gehorchen — und lenke.', en: 'Passive aggression: disobedience in the cloak of obedience is hard to attack. Seem to obey — and steer.' } },
    { t: { de: 'Strategie 33 · Säge Ungewissheit', en: 'Strategy 33 · Sow uncertainty' },
      b: { de: 'Verbreite Zweifel und widersprüchliche Signale: Wer nicht weiß, was kommt, lähmt sich selbst.', en: 'Spread doubt and contradictory signals: those who don\'t know what\'s coming paralyze themselves.' } },
  ],

  /* ================= ART OF SEDUCTION ================= */
  'sed-1': [
    { t: { de: 'Verführung · Die indirekte Macht', en: 'Seduction · Indirect power' },
      b: { de: 'Verführung wirkt über Emotion, nicht über Argumente: Sie erzeugt Vergnügen und löst Widerstand auf — die stärkste Form des Einflusses.', en: 'Seduction works through emotion, not arguments: it creates pleasure and dissolves resistance — the strongest form of influence.' } },
    { t: { de: 'Die Sirene', en: 'The Siren' },
      b: { de: 'Die älteste Verführerfigur: Sie überwältigt die Sinne mit physischer und sinnlicher Präsenz — wie Kleopatra.', en: 'The oldest seducer figure: she overwhelms the senses with physical and sensual presence — like Cleopatra.' } },
    { t: { de: 'Der Rake', en: 'The Rake' },
      b: { de: 'Er begehrt so total und verwegen, dass sein Gegenüber sich einzigartig fühlt. Ein Hauch Gefahr macht es aufregend.', en: 'He desires so totally and recklessly that the other feels unique. A touch of danger makes it thrilling.' } },
    { t: { de: 'Dandy & Natural', en: 'Dandy & Natural' },
      b: { de: 'Der Dandy verführt durch Androgynie und Stilfreiheit; der Natural durch kindliche Unschuld und Spontaneität.', en: 'The Dandy seduces through androgyny and style freedom; the Natural through childlike innocence and spontaneity.' } },
    { t: { de: 'Die Kokette', en: 'The Coquette' },
      b: { de: 'Sie wechselt zwischen Nähe und Kälte: Das Entzug-Versprechen-Spiel hält das Begehren permanent gespannt.', en: 'She alternates between warmth and coldness: the withdrawal-promise game keeps desire permanently tense.' } },
    { t: { de: 'Charmer & Star', en: 'Charmer & Star' },
      b: { de: 'Der Charmer gibt das Gefühl, wirklich verstanden zu werden. Der Star bleibt distanziert — andere projizieren ihre Fantasien auf ihn.', en: 'The Charmer makes others feel truly understood. The Star stays distant — others project their fantasies onto him.' } },
  ],
  'sed-2': [
    { t: { de: 'Der Anti-Verführer · Das Kernproblem', en: 'The Anti-Seducer · The core problem' },
      b: { de: 'Selbstbezogenheit und Unsicherheit: Er raubt Aufmerksamkeit, Energie und Zeit, statt zu geben — und tötet jede Spannung.', en: 'Self-absorption and insecurity: he takes attention, energy and time instead of giving — and kills all tension.' } },
    { t: { de: 'Signal · Klammern und ständige Verfügbarkeit', en: 'Signal · Clinging and constant availability' },
      b: { de: 'Anziehung braucht Raum. Wer sich aufdrängt, zerstört Knappheit und Geheimnis — die Treibstoffe des Begehrens.', en: 'Attraction needs space. Pushing yourself forward destroys scarcity and mystery — the fuel of desire.' } },
    { t: { de: 'Prahlen, Moralisieren, Klagen', en: 'Boasting, moralizing, whining' },
      b: { de: 'Der Prahler raubt dem anderen die Bühne, der Moralist belehrt statt zu verführen, der Kläger macht Begegnungen zur Last.', en: 'The braggart steals the other\'s stage, the moralist lectures instead of seduces, the whiner turns encounters into a burden.' } },
    { t: { de: 'Das Gegenmittel · Großzügigkeit', en: 'The antidote · Generosity' },
      b: { de: 'Geben ist das Gegenteil des Anti-Verführers: echte Aufmerksamkeit und Großzügigkeit für den anderen sind zutiefst verführerisch.', en: 'Giving is the opposite of the anti-seducer: genuine attention and generosity toward the other are deeply seductive.' } },
    { t: { de: 'Erkennen und eliminieren', en: 'Recognize and eliminate' },
      b: { de: 'Entdeckst du Anti-Verführer-Züge an dir, ignoriere sie nicht: Sie sabotieren jede Anziehung — arbeite aktiv daran, sie abzulegen.', en: 'If you notice anti-seducer traits in yourself, don\'t ignore them: they sabotage all attraction — actively work to shed them.' } },
  ],
  'sed-3': [
    { t: { de: 'Der Prozess · 24 Schritte in 4 Phasen', en: 'The process · 24 steps in 4 phases' },
      b: { de: 'Annäherung, Verführung, Vertiefung, Vollendung: Verführung ist ein Prozess, kein Moment.', en: 'Approach, seduction, deepening, consummation: seduction is a process, not a moment.' } },
    { t: { de: 'Phase 1 · Neugier wecken, Sicherheit geben', en: 'Phase 1 · Spark curiosity, give safety' },
      b: { de: 'Zuerst Interesse säen, ohne Bedürftigkeit zu zeigen: Der andere soll kommen wollen — nicht kommen müssen.', en: 'First sow interest without showing neediness: the other should want to come closer — not be forced to.' } },
    { t: { de: 'Das Werkzeug · Inszenierte Zufälle', en: 'The tool · Staged coincidences' },
      b: { de: 'Der Eindruck „das Schicksal führt uns zusammen" öffnet Herzen stärker als jedes Argument.', en: 'The impression "fate brings us together" opens hearts stronger than any argument.' } },
    { t: { de: 'Phase 2 · Vergnügen und Verwirrung', en: 'Phase 2 · Pleasure and confusion' },
      b: { de: 'Wer leicht desorientiert ist, wird empfänglicher und gibt Kontrolle ab: Wechsle Nähe und Distanz, Überraschung und Geheimnis.', en: 'Slight disorientation makes people receptive and give up control: alternate closeness and distance, surprise and mystery.' } },
    { t: { de: 'Gesten · Dosierung statt Flut', en: 'Gestures · Dosed, not flooded' },
      b: { de: 'Gezielte, überraschende Aufmerksamkeiten wirken — aber nur dosiert und unerwartet, nie aufdringlich.', en: 'Targeted, surprising attentions work — but only dosed and unexpected, never pushy.' } },
  ],
  'sed-4': [
    { t: { de: 'Phase 3 · Schwäche zeigen', en: 'Phase 3 · Showing weakness' },
      b: { de: 'Gezielt Schwäche zu zeigen erweckt den Beschützerinstinkt: Der andere soll das Gefühl haben, gebraucht zu werden.', en: 'Showing deliberate weakness awakens the protector instinct: the other should feel needed.' } },
    { t: { de: 'Phase 3 · Die Illusion bewahren', en: 'Phase 3 · Preserve the illusion' },
      b: { de: 'Alltäglichkeit ist der Feind der Verführung: Hingabe entsteht, wenn die Realität blasser wirkt als das Erlebte mit dir.', en: 'Ordinariness is the enemy of seduction: devotion arises when reality seems pale compared to the experience with you.' } },
    { t: { de: 'Hingabe vertiefen', en: 'Deepening devotion' },
      b: { de: 'Schwäche, Illusion und kleine Prüfungen verweben den anderen emotional immer stärker mit dir.', en: 'Weakness, illusion and small trials weave the other ever more deeply into you emotionally.' } },
    { t: { de: 'Phase 4 · Das Nachspiel entscheidet', en: 'Phase 4 · The aftermath decides' },
      b: { de: 'Nach dem Erreichen beginnt die eigentliche Kunst: Wer abrupt kalt wird, erzeugt Verbitterung — und einen Feind.', en: 'After success the true art begins: turning cold abruptly creates bitterness — and an enemy.' } },
    { t: { de: 'Verführung = freiwillige Hingabe', en: 'Seduction = voluntary devotion' },
      b: { de: 'Wer verführt, gewinnt Macht durch Emotion statt Zwang: freiwillige Hingabe — die stärkste Form des Einflusses.', en: 'Seduction wins power through emotion instead of force: voluntary devotion — the strongest form of influence.' } },
  ],

  // ── The 50th Law ─────────────────────────────────────────────
  'fifty-1': [
    { t: { de: 'Das 50. Gesetz · Fürchte nichts', en: 'The 50th Law · Fear nothing' },
      b: { de: 'Angst lähmt Urteil und Handlung. Wer Furchtlosigkeit zur Lebenshaltung macht, gewinnt Freiheit.', en: 'Fear paralyzes judgment and action. Making fearlessness your way of life brings freedom.' } },
    { t: { de: 'Kapitel 1 · Intensiver Realismus', en: 'Chapter 1 · Intense realism' },
      b: { de: 'Sieh die Dinge, wie sie sind — keine Illusionen über Menschen und Lage. Wer Fantasien pflegt, wird von der Realität bestraft.', en: 'See things as they are — no illusions about people or situations. Those who nurse fantasies get punished by reality.' } },
    { t: { de: 'Kapitel 2 · Mach dir alles zu eigen', en: 'Chapter 2 · Make everything your own' },
      b: { de: 'Übernimm volle Verantwortung — auch für das, was dir widerfährt. Opferdenken gibt Macht ab, Eigentümerdenken macht Rückschläge zum Rohmaterial.', en: 'Take full responsibility — even for what happens to you. Victim thinking gives away power; ownership thinking turns setbacks into raw material.' } },
    { t: { de: 'Kapitel 3 · Mist in Zucker verwandeln', en: 'Chapter 3 · Turn shit into sugar' },
      b: { de: 'Widrigkeit ist Chance: 50 Cent machte aus dem Schussattentat eine Legende — Schwieriges ist Treibstoff.', en: 'Adversity is opportunity: 50 Cent turned the shooting into legend — hardship is fuel.' } },
    { t: { de: 'Kapitel 4–5 · Bewegung und Härte', en: 'Chapters 4–5 · Movement and toughness' },
      b: { de: 'Bleib in Bewegung: Wer sich ständig weiterentwickelt, lässt sich nicht festnageln. Und wisse, wann Härte nötig ist.', en: 'Keep moving: constant evolution makes you uncatchable. And know when toughness is required.' } },
  ],
  'fifty-2': [
    { t: { de: 'Kapitel 6 · Von vorn führen', en: 'Chapter 6 · Lead from the front' },
      b: { de: 'Autorität entsteht durch Beispiel, nicht durch Titel: Menschen folgen dem, der das Risiko teilt und den Standard selbst lebt.', en: 'Authority comes from example, not titles: people follow the one who shares the risk and lives the standard himself.' } },
    { t: { de: 'Kapitel 7 · Die Umgebung von innen kennen', en: 'Chapter 7 · Know the environment from inside' },
      b: { de: '50 Cent kannte die Straße. Wer sein Feld tief von innen versteht, navigiert besser als jeder Theoretiker.', en: '50 Cent knew the street. Those who deeply understand their field from the inside navigate better than any theorist.' } },
    { t: { de: 'Kapitel 8 · Respektiere den Prozess', en: 'Chapter 8 · Respect the process' },
      b: { de: 'Meisterschaft entsteht durch Zeit und Wiederholung, nicht durch Abkürzungen. Respekt vor der Dauer ist der härteste Muskel der Furchtlosigkeit.', en: 'Mastery comes through time and repetition, not shortcuts. Respect for duration is the hardest muscle of fearlessness.' } },
    { t: { de: 'Kapitel 9 · Grenzen überschreiten', en: 'Chapter 9 · Push past limits' },
      b: { de: 'Die meisten Grenzen sitzen im Kopf: Wer Angst als Signal statt als Mauer liest, wächst über das Gewohnte hinaus.', en: 'Most limits live in the mind: reading fear as a signal instead of a wall lets you grow beyond the familiar.' } },
    { t: { de: 'Kapitel 10 · Stelle dich deiner Sterblichkeit', en: 'Chapter 10 · Confront your mortality' },
      b: { de: 'Das Bewusstsein der Endlichkeit macht drängende Angst klein — es ist die Wurzel der Furchtlosigkeit.', en: 'Awareness of finitude shrinks petty fear — it is the root of fearlessness.' } },
  ],

  // ── Mastery ──────────────────────────────────────────────────
  'mas-1': [
    { t: { de: 'Phase 1 · Entdecke deine Berufung', en: 'Phase 1 · Discover your calling' },
      b: { de: 'Deine Lebensaufgabe liegt in dem, was dich als Kind mühelos anzog — sie ist Richtung, nicht Beruf.', en: 'Your life\'s task lies in what drew you effortlessly as a child — it is direction, not a job.' } },
    { t: { de: 'Talent genügt nicht', en: 'Talent is not enough' },
      b: { de: 'Meisterschaft entsteht durch Prozess und Dauer — Talent ohne Lehrzeit verkümmert.', en: 'Mastery comes from process and duration — talent without apprenticeship withers.' } },
    { t: { de: 'Phase 2 · Die ideale Lehrzeit', en: 'Phase 2 · The ideal apprenticeship' },
      b: { de: 'Unterwirf dich der Realität: beobachten, üben, demütig lernen. Die Lehrzeit ist keine Zeit des Glanzes — sie baut das Fundament.', en: 'Submit to reality: observe, practice, learn humbly. Apprenticeship is no time for glory — it builds the foundation.' } },
    { t: { de: 'Strategie · Lernen vor Geld', en: 'Strategy · Learning before money' },
      b: { de: 'Wähle Positionen nach Lernwert, nicht nach Lohn — Wissen zahlt sich später exponentiell aus.', en: 'Choose positions for learning value, not pay — knowledge pays exponentially later.' } },
    { t: { de: 'Liebe den Prozess', en: 'Love the process' },
      b: { de: 'Ständig experimentieren, Wiederholung annehmen: Wer den Prozess liebt, bleibt lange genug dran, um Meisterschaft zu erreichen.', en: 'Keep experimenting, embrace repetition: loving the process keeps you going long enough to reach mastery.' } },
  ],
  'mas-2': [
    { t: { de: 'Phase 3 · Absorbiere die Macht des Meisters', en: 'Phase 3 · Absorb the master\'s power' },
      b: { de: 'Ein Mentor komprimiert Jahrzehnte Erfahrung in direkte Rückmeldung — ohne Führung verschwendest du Jahre an Fehler.', en: 'A mentor compresses decades of experience into direct feedback — without guidance you waste years on mistakes.' } },
    { t: { de: 'Dann: Emanzipation', en: 'Then: emancipation' },
      b: { de: 'Absorbieren, dann loslösen: Irgendwann muss der Schüler den Meister übertreffen — wer bleibt, bleibt ewig Schüler.', en: 'Absorb, then break away: eventually the student must surpass the master — those who stay remain students forever.' } },
    { t: { de: 'Phase 4 · Sieh die Menschen, wie sie sind', en: 'Phase 4 · See people as they are' },
      b: { de: 'Warnung vor naiven Projektionen: Menschen zeigen Masken. Lies Muster über Zeit statt Worte im Moment.', en: 'Beware naive projections: people wear masks. Read patterns over time, not words in the moment.' } },
    { t: { de: 'Die sieben tödlichen Realitäten', en: 'The seven deadly realities' },
      b: { de: 'Neid, Konformismus, Eifersucht und andere Kräfte wirken in jeder Gruppe — sie zu kennen ist Schutz vor der Gruppendynamik.', en: 'Envy, conformism, jealousy and other forces operate in every group — knowing them is protection from group dynamics.' } },
    { t: { de: 'Charakter = Muster', en: 'Character = pattern' },
      b: { de: 'Urteile über Menschen über ihre Muster, nicht über ihre Worte: Charakter ist Wiederholung.', en: 'Judge people by their patterns, not their words: character is repetition.' } },
  ],
  'mas-3': [
    { t: { de: 'Phase 5 · Der dimensionale Geist', en: 'Phase 5 · The dimensional mind' },
      b: { de: 'Wenn tiefes Wissen mit kreativem Spiel verschmilzt, beginnt die eigene Schöpfung: Kindheitsoffenheit plus Können.', en: 'When deep knowledge merges with creative play, original creation begins: childlike openness plus skill.' } },
    { t: { de: 'Emotionale Fallgruben', en: 'Emotional pitfalls' },
      b: { de: 'Selbstzweifel, Konformismus, Frustration: Kreativität stirbt an Emotionen — Vergleich, Ungeduld und Angst vor dem Neuen sind die Fallen.', en: 'Self-doubt, conformism, frustration: creativity dies of emotions — comparison, impatience and fear of the new are the traps.' } },
    { t: { de: 'Phase 6 · Intuition + Rationalität', en: 'Phase 6 · Intuition + rationality' },
      b: { de: 'Nach etwa 10.000 Stunden sieht der Meister Muster sofort: Das Feld wird zur zweiten Natur.', en: 'After roughly 10,000 hours the master sees patterns instantly: the field becomes second nature.' } },
    { t: { de: 'Der häufigste Fehler', en: 'The most common mistake' },
      b: { de: 'Die kreative Phase erzwingen und die Lehrzeit überspringen: Ohne Fundament kein Gebäude.', en: 'Forcing the creative phase and skipping the apprenticeship: no foundation, no building.' } },
    { t: { de: 'Intuition ist verdichtete Erfahrung', en: 'Intuition is compressed experience' },
      b: { de: 'Nichts Mystisches — sondern das Ergebnis langer Praxis. Der Pfad ist offen für alle, aber er verlangt Zeit.', en: 'Nothing mystical — but the result of long practice. The path is open to all, but it demands time.' } },
  ],

  // ── The Laws of Human Nature ─────────────────────────────────
  'hn-1': [
    { t: { de: 'Gesetz 1 · Meistere deine Irrationalität', en: 'Law 1 · Master your irrationality' },
      b: { de: 'Der erste Schritt: eingestehen, dass wir alle irrational sind — und die eigenen Auslöser erkennen. Wer glaubt, rational zu sein, wird am stärksten gesteuert.', en: 'The first step: admit we are all irrational — and recognize your triggers. Those who believe they are rational are steered most.' } },
    { t: { de: 'Gesetz 2 · Verwandle Narzissmus', en: 'Law 2 · Transform narcissism' },
      b: { de: 'Wir sind alle Narzissten. Das Ziel ist nicht Abschaffung, sondern Verwandlung: Selbstliebe wird zu Empathie.', en: 'We are all narcissists. The goal is not abolition but transformation: self-love turns into empathy.' } },
    { t: { de: 'Gesetz 3 · Durchschaue die Masken', en: 'Law 3 · See through the masks' },
      b: { de: 'Worte sind leicht kontrollierbar. Achte auf Körpersprache, Tonfall und Mikro-Signale — der Körper verrät, was die Maske verbirgt.', en: 'Words are easily controlled. Watch body language, tone and micro-signals — the body betrays what the mask hides.' } },
    { t: { de: 'Gesetz 4 · Charakter über Muster lesen', en: 'Law 4 · Read character via patterns' },
      b: { de: 'Menschen sind Gefangene ihres Charakters: Muster wiederholen sich. Glaube dem Muster, nicht dem Versprechen.', en: 'People are prisoners of their character: patterns repeat. Trust the pattern, not the promise.' } },
    { t: { de: 'Gesetz 5 · Schwer fassbares Objekt der Begierde', en: 'Law 5 · Elusive object of desire' },
      b: { de: 'Begehren folgt der Spannung: Was vollkommen greifbar ist, verliert seinen Reiz — Distanz und Geheimnis erzeugen Anziehung.', en: 'Desire follows tension: what is fully graspable loses its allure — distance and mystery create attraction.' } },
  ],
  'hn-2': [
    { t: { de: 'Gesetz 6 · Erhöhe deine Perspektive', en: 'Law 6 · Elevate your perspective' },
      b: { de: 'Die meisten Menschen reagieren auf das Unmittelbare. Wer in langen Zeitrahmen denkt, gewinnt das große Spiel.', en: 'Most people react to the immediate. Those who think in long timeframes win the big game.' } },
    { t: { de: 'Gesetz 7 · Weiche Widerstand indirekt', en: 'Law 7 · Soften resistance indirectly' },
      b: { de: 'Direktes Drängen verhärtet Widerstand. Arbeite indirekt: Rahmen setzen und den anderen selbst entdecken lassen.', en: 'Direct pressure hardens resistance. Work indirectly: set frames and let the other discover it themselves.' } },
    { t: { de: 'Gesetz 8 · Ändere deine Einstellung', en: 'Law 8 · Change your attitude' },
      b: { de: 'Selbstsabotierende Skripte erzeugen immer die gleichen Umstände: Ändere das Drehbuch, nicht die Bühne.', en: 'Self-sabotaging scripts produce the same circumstances: change the script, not the stage.' } },
    { t: { de: 'Gesetz 9 · Integriere den Schatten', en: 'Law 9 · Integrate the shadow' },
      b: { de: 'Was wir verdrängen, bricht unkontrolliert hervor. Wer die dunkle Seite konfrontiert und integriert, wird authentisch und stark.', en: 'What we repress erupts uncontrollably. Confronting and integrating the dark side makes you authentic and strong.' } },
    { t: { de: 'Beginne bei dir selbst', en: 'Start with yourself' },
      b: { de: 'Die Gesetze gelten für alle — auch für dich. Wer sich selbst nicht durchschaut, durchschaut niemanden.', en: 'The laws apply to everyone — including you. Those who cannot see through themselves see through no one.' } },
  ],
  'hn-3': [
    { t: { de: 'Gesetz 10 · Neid und das fragile Ego', en: 'Law 10 · Envy and the fragile ego' },
      b: { de: 'Neid wird selten zugegeben. Achte auf vergiftetes Lob, übertriebene Bewunderung und subtile Abwertung.', en: 'Envy is rarely admitted. Watch for poisoned praise, exaggerated admiration and subtle devaluation.' } },
    { t: { de: 'Gesetz 11 · Kenne deine Grenzen', en: 'Law 11 · Know your limits' },
      b: { de: 'Grandiosität wächst mit dem Erfolg und verzerrt die Selbsteinschätzung. Realistische Grenzen sind Stärke, keine Schwäche.', en: 'Grandiosity grows with success and distorts self-assessment. Realistic limits are strength, not weakness.' } },
    { t: { de: 'Gesetz 13 · Sinn und Zweck', en: 'Law 13 · Sense of purpose' },
      b: { de: 'Schreite mit einem Gefühl von Sinn voran: Zweck ist ein innerer Kompass, der Kräfte bündelt — Zwecklosigkeit zerstreut.', en: 'Advance with a sense of purpose: purpose is an inner compass that bundles forces — purposelessness disperses.' } },
    { t: { de: 'Gesetz 14 · Der Sog der Gruppe', en: 'Law 14 · The pull of the group' },
      b: { de: 'In Gruppen denken wir anders: Gruppen erzeugen eigene Realitäten. Wer das weiß, behält seinen Standpunkt — und kann Gruppen lenken.', en: 'In groups we think differently: groups create their own realities. Knowing this keeps your standpoint — and lets you steer groups.' } },
    { t: { de: 'Das Neid-Muster', en: 'The envy pattern' },
      b: { de: 'Übertriebenes Lob gefolgt von Sticheleien ist der Klassiker: Neid tarnt sich als Lob oder Kritik.', en: 'Exaggerated praise followed by jabs is the classic: envy disguises itself as praise or criticism.' } },
  ],
  'hn-4': [
    { t: { de: 'Gesetz 15 · Zum Folgen verführen', en: 'Law 15 · Seduce into following' },
      b: { de: 'Führung ist verführerisch, nicht zwingend: Sprich die Sehnsucht nach Zugehörigkeit und Sinn an — dann folgen die Menschen freiwillig.', en: 'Leadership is seductive, not coercive: appeal to the longing for belonging and meaning — then people follow voluntarily.' } },
    { t: { de: 'Gesetz 16 · Feindseligkeit hinter der Fassade', en: 'Law 16 · Hostility behind the facade' },
      b: { de: 'Passiv-aggressive Signale sind verbreiteter als offene Feindschaft: Gefährlicher als der offene Feind ist der Lächelnde, der subtil torpediert.', en: 'Passive-aggressive signals are more common than open hostility: more dangerous than the open enemy is the smiler who subtly torpedoes.' } },
    { t: { de: 'Gesetz 17 · Ergreife den historischen Moment', en: 'Law 17 · Seize the historical moment' },
      b: { de: 'Jede Epoche hat ihre Strömung: Lies den Zeitgeist und reite die Welle, statt dagegen anzukämpfen.', en: 'Every era has its current: read the zeitgeist and ride the wave instead of fighting it.' } },
    { t: { de: 'Gesetz 18 · Meditation über die Sterblichkeit', en: 'Law 18 · Meditate on mortality' },
      b: { de: 'Der Tod verbindet alle Menschen: Wer ihn annimmt, gewinnt Demut, Dringlichkeit und Mitgefühl — und lebt intensiver.', en: 'Death connects all people: accepting it brings humility, urgency and compassion — and makes you live more intensely.' } },
    { t: { de: 'Radikale Selbstehrlichkeit', en: 'Radical self-honesty' },
      b: { de: 'Alle 18 Gesetze beginnen beim Selbst: Macht beginnt nicht bei anderen, sondern im eigenen Inneren.', en: 'All 18 laws start with the self: power begins not with others, but within yourself.' } },
  ],

  // ── Grand Synthesis (Bonus) ──────────────────────────────────
  'syn-1': [
    { t: { de: 'Emotion kontrollieren = Macht kontrollieren', en: 'Controlling emotion = controlling power' },
      b: { de: 'Wer dich emotional macht, führt dich: Geistesgegenwart ist die letzte Verteidigung. Zieht sich durch War, Gesetz 39 und Human Nature 1.', en: 'Whoever makes you emotional controls you: presence of mind is the last defense. Runs through War, Law 39 and Human Nature 1.' } },
    { t: { de: 'Indirektion schlägt Konfrontation', en: 'Indirection beats confrontation' },
      b: { de: 'Flanke statt Front, Insinuation statt Forderung, Rahmen statt Argument: Der direkte Weg erzeugt Widerstand, der indirekte öffnet Türen.', en: 'Flank instead of front, insinuation instead of demand, frame instead of argument: the direct route creates resistance, the indirect opens doors.' } },
    { t: { de: 'Aufmerksamkeit ist eine Währung', en: 'Attention is a currency' },
      b: { de: 'Sichtbarkeit erzeugt Wert, Überverfügbarkeit zerstört ihn: Knappheit steuert Begehren (Gesetz 6 & 16, Seduction, Human Nature 5).', en: 'Visibility creates value, over-availability destroys it: scarcity steers desire (Laws 6 & 16, Seduction, Human Nature 5).' } },
    { t: { de: 'Ruf und Bild steuern', en: 'Control reputation and image' },
      b: { de: 'Die Welt reagiert auf dein Bild: Steuere es — sonst tun es andere (Gesetz 5, 25, 30, 37).', en: 'The world reacts to your image: control it — or others will (Laws 5, 25, 30, 37).' } },
    { t: { de: 'Muster schlagen Momente', en: 'Patterns beat moments' },
      b: { de: 'Charakter ist Wiederholung: Einzelszenen täuschen, Muster lügen nicht. Beurteile Menschen über Zeit.', en: 'Character is repetition: single scenes deceive, patterns don\'t lie. Judge people over time.' } },
    { t: { de: 'Meisterschaft = höchster Machthebel', en: 'Mastery = highest power lever' },
      b: { de: 'Wahres Können macht unabhängig — es ist die eine Macht, die niemand dir nehmen kann. Alle sechs Bücher sind ein System.', en: 'True skill makes you independent — the one power no one can take from you. All six books are one system.' } },
  ],
}
